### ISSUE TITLE
Qt Assistant cannot work well under Windows

### ISSUE THREAD

**Issue by bioinformatist** [altendky/pyqt-tools#5] opened 2017-05-24 01:20 UTC
Dear,
My pyqt5-tools is the latest version. When I try to use Qt Assistant, or check the manual of Qt Linguist, it raise an error like:"Unable to launch Qt Assistant (C:/ProgramData/Anaconda3/Lib/site-packages/pyqt5-tools/bin\assistant)"

The path separator between `bin` and `assistant` is backslash, does this lead to this error?

Thanks for attention to this matter.

**Comment by altendky** [comment] 2017-05-24 17:28
To be sure, what version of pyqt5-tools and how did you install it? The Windows APIs have accepted both slashes for a long time soi wouldn't bet on that. I'm out today but can try to take a look tomorrow. Bug me if I don't get back to you.

**Comment by altendky** [comment] 2017-05-25 21:15
I just tested with Python 3.6.1 32-bit and pyqt5-tools 5.8.2.1.0rc1 on Windows 10:

* Directly ran `assistant.exe`
  * No errors, I was able to follow a few links
* Directly ran `linguist.exe`
 * Selected Help > Manual and got a dialog with the same error as you.

For some reason it's looking in the `bin` subdirectory.  I cheated, created `bin`, and copied `assistant.exe` and the `platforms` and `plugins` into `bin`...  now I get another dialog instead saying `Error reading collection file 'C:/Users/altendky/AppData/Local/QtProject/Assistant\qthe` and then it's cutoff it seems and i can't see the rest.

So, I can confirm and recreate the issue but I can't fix it right now, sorry.  If you can fudge it enough to work that might help figure out how to get it fixed.  I'll let you know if I make some progress.

**Comment by bioinformatist** [comment] 2017-06-05 16:32
Thank you. 

Actually, this is not a serious problem, I found it by accident but I never use these tools. I just use QtDesigner to help build the mainwindow of my app. I can't find any source code, configuration files or other plain-text files about this problem in the repo, so I guess if something goes wrong when Qt bring these binaries to us (for Python API). 

I'll keep this in focus, too.

**Comment by hesmith1029** [comment] 2019-03-31 18:20
Was this ever fixed, or what is the fix

**Comment by altendky** [comment] 2019-03-31 19:14
@hesmith1029 just looking back here it seems that assistant worked ok for me awhile back.  Can you share your specific issue?

**Comment by HoDaDor** [comment] 2020-01-19 08:35
Still an issue but in case anyone cares, I mostly fixed it by creating a symbolic junction:

wherever your site-packages directory is = INSERT_SITE-PACKAGES_DIR_PATH_HERE

mklink /J  "INSERT_SITE-PACKAGES_DIR_PATH_HERE\pyqt5-tools\bin" "INSERT_SITE-PACKAGES_DIR_PATH_HERE\pyqt5-tools\"

**Comment by qhtran** [comment] 2020-01-30 06:22
**I simply made a hard link to the folder. It works.
Note: you should use windows command with administrator right**

`mklink /J "c:\Program Files (x86)\Python38-32\Lib\site-packages\pyqt5_tools\Qt\bin\bin" "c:\Program Files (x86)\Python38-32\Lib\site-packages\pyqt5_tools\Qt\bin"
`

**result:**
Junction created for c:\Program Files (x86)\Python38-32\Lib\site-packages\pyqt5_tools\Qt\bin\bin <<===>> c:\Program Files (x86)\Python38-32\Lib\site-packages\pyqt5_tools\Qt\bin

**Comment by HopWorks** [comment] 2020-10-08 15:13
Version 5.11.1
I set up the hard link and the error went away, but it appears that the location of the content that designer.exe refers to has moved. At least when you go to **help/QT Designer Help Ctrl+?** from the menu bar...
**The page could not be found.
'qthelp://org.qt-project.qtdesigner.5111/qtdesigner/qtdesigner-manual.html'**

**Comment by SciFiReader** [comment] 2020-11-21 05:16
I'm using Windows 11, Python version 3.8, and Qt and Qt Designer version 5.14.1.  Yes I've tried many of the above solutions, but no go. I can't find "assistant.exe" in my python's "site-packages/PyQt5" directory.  My solution was to create a shortcut to "https://doc.qt.io/qt-5/qtdesigner-manual.html" on the desktop, and that works ok.

**Comment by altendky** [comment] 2020-11-21 13:25
I think https://github.com/altendky/qt-applications/commit/ff4bd7074667fbb768098c193a28ef7f3d6c49da will fix this.  Hopefully it is released within a week or two.

**Comment by SciFiReader** [comment] 2020-11-21 13:29
Excellent, thanks Kyle.  I'm just a Qt newbie, and this will be helpful.

**Comment by altendky** [comment] 2020-11-21 13:42
Hmm, it runs but there isn't any content.  Maybe aqtinstall isn't grabbing the docs.  I'll have to look into that aspect.  Hopefully it can and they aren't too big.  But yeah, personally, I just open a browser and search for `qt5 whateveriwant` and look at the C++ docs.

![image](https://user-images.githubusercontent.com/543719/99878615-cc904480-2bd4-11eb-9736-fa4c47a0c8e5.png)

**Comment by altendky** [comment] 2020-11-21 14:29
Looks like the full docs downloaded by `aqt doc` ([`aqtinstall`](https://pypi.org/project/aqtinstall/)) are about 400MB (at least in Linux).  That's...  4x the PyPI package limit I think.  `:]` So, I don't really think it's a great idea to try to include them.  For more granular reference, `QtWidgets` docs are 43MB and Designer docs are 7MB.  So maybe we could include docs for a tool or two but even just the `QtWidgets` docs, let alone other modules in addition, are too big.

So, I suspect that 'get the docs via `aqt doc`' will be the recommendation if you want local docs.  Perhaps the pyqt5-tools (or maybe qt5-tools, or...) CLI can offer helpers for setting the environment variable (haven't looked up which one yet) to reference wherever you have `aqtinstall` put them.  But, I think that doesn't need to be integrated into the giant `qt5-applications` package so I'll probably wait until after I get the next round of releases out to try to deal with that.

**Comment by SciFiReader** [comment] 2020-11-22 00:56
Ok. I can live with that and await the next update with interest.  Well
done for tracking down the cause of the issue.

>

**Closed** 2023-03-27 19:36 UTC
